name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - R ${{ matrix.R }} - ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        version:
          - '1.0'
          - '1.1'
          - '1.2'
          - '1.3'
          - '1.4'
          - '1.5'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        R: [ '3.5.3', '3.6.1' ]
        arch:
          - x64
        experimental: [false]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Install R ${{ matrix.R }} 
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - name: Install ape 
        run: |
          R -e 'install.packages("ape", repos="http://cran.r-project.org")'
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV }}
